/*
 * 프로젝트
 */
CREATE TABLE PROJECT (
    pno NUMBER PRIMARY KEY,
    title varchar2(50) NOT NULL,
    dept varchar2(50) NOT NULL,
    pmno varchar2(9) NOT NULL
);
DELETE FROM PROJECT
WHERE PNO = 31;
CREATE SEQUENCE seq_pno
			INCREMENT BY 1
			START WITH 1
			MAXVALUE 9999;
DROP SEQUENCE seq_pno;
INSERT INTO account values('E'||to_char(acc_seq.nextval),'abcabc123','김길동','himan7777@naver.com', '개발부',
	'부장','서울시 마포구 서교동 447-5 201호','010-1234-5678',NULL,sysdate,'pm');
INSERT INTO account values('E'||to_char(acc_seq.nextval),'abcabc123','김유신','ys7777@naver.com', '개발부',
	'사원','서울시 마포구 서교동 447-5 201호','010-1234-5678',NULL,sysdate,'user');

INSERT INTO PROJECT values(seq_pno.nextval, '첫프로젝트', '개발부', 'E10000004');

UPDATE PROJECT
	SET TITLE = #{title},
		DEPT  = #{dept}
WHERE PNO = #{pno};

DELETE FROM SCHEDULE
WHERE PNO = 20;
/*
프로젝트 생성
INSERT INTO PROJECT values(seq_pno.nextval, #{title}, #{dept}, #{userno});

방금 생성된 프로젝트의 pno값 추출
SELECT max(pno) FROM PROJECT
WHERE PMNO = 'E10000004'
ORDER BY PNO

부서별 프로젝트 갯수
SELECT DEPT, count(*) deptcnt
FROM PROJECT
GROUP BY DEPT

부서별 예산
SELECT p.DEPT, SUM(s.BUDGET) deptbudget
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO(+)
GROUP BY p.DEPT

프로젝트별 예산
SELECT p.PNO, p.TITLE, SUM(s.BUDGET) projectbudget
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO(+)
AND p.PMNO = #{pmno}
GROUP BY p.PNO, p.TITLE

프로젝트별 참가인원수
SELECT p.PNO, p.TITLE, COUNT(pp.USERNO) usercnt
FROM PROJECT p, PRJPARTICIPANT pp
WHERE p.PNO = pp.PNO
AND p.PMNO = #{pmno}
GROUP BY p.PNO, p.TITLE

프로젝트 수정
UPDATE PROJECT
	SET TITLE = #{title},
		DEPT  = #{dept}
WHERE PNO = #{pno}

프로젝트 삭제(일정삭제->프로젝트삭제)
DELETE FROM PROJECT
WHERE PNO = #{pno}

DELETE FROM SCHEDULE
WHERE PNO = #{pno}

프로젝트 진행도
SELECT NVL(AVG(s.PROGRESS),0)
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO(+)
AND p.PNO = #{pno}
GROUP BY p.PNO
*/
SELECT * FROM PROJECT
ORDER BY PNO;

SELECT max(pno) FROM PROJECT
WHERE PMNO = 'E10000004'
ORDER BY PNO;

SELECT p.*, AVG(progress) progAvg
FROM PROJECT p, PRJPARTICIPANT pp, SCHEDULE s
WHERE p.PNO = pp.PNO AND p.PNO = s.PNO(+)
AND pp.USERNO = 'E10000004'
GROUP BY p.PNO, p.TITLE, p.DEPT, p.PMNO
ORDER BY p.pno desc;

SELECT p.*, a.NAME
FROM PROJECT p, ACCOUNT a
WHERE p.PMNO = a.USERNO
ORDER BY pno;

SELECT DEPT, count(*)
FROM PROJECT
GROUP BY DEPT;

SELECT p.DEPT, SUM(s.BUDGET) deptbudget
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO(+)
GROUP BY p.DEPT; 

SELECT p.PNO, p.TITLE, SUM(s.BUDGET) projectbudget
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO(+)
AND p.PMNO = 'E10000004'
GROUP BY p.PNO, p.TITLE;

SELECT p.PNO, p.TITLE, COUNT(pp.USERNO) usercnt
FROM PROJECT p, PRJPARTICIPANT pp
WHERE p.PNO = pp.PNO
AND p.PMNO = 'E10000004'
GROUP BY p.PNO, p.TITLE;

SELECT NVL(AVG(s.PROGRESS),0)
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO(+)
AND p.PNO = 30
GROUP BY p.PNO;




/*
 * 일정
 */
CREATE TABLE SCHEDULE(
	sno NUMBER PRIMARY KEY,
	pno NUMBER NOT NULL,
	sname varchar2(50) NOT NULL,
	status varchar2(50) NOT NULL,
	progress NUMBER NOT NULL,
	startDate DATE NOT NULL,
	endDate DATE NOT NULL,
	budget NUMBER NOT NULL
);
CREATE SEQUENCE seq_sno
			INCREMENT BY 1
			START WITH 1
			MAXVALUE 9999;
DROP SEQUENCE seq_sno;
INSERT INTO SCHEDULE values(seq_sno.nextval, 2, '첫일정', '진행중', 0, sysdate, to_date('2022-08-05','YYYY-MM-DD'), 100000);
INSERT INTO SCHEDULE values(seq_sno.nextval, 2, '완료일정', '완료', 100, sysdate, to_date('2022-08-03','YYYY-MM-DD'), 150000);
INSERT INTO SCHEDULE values(seq_sno.nextval, 21, '신규일정1', '막힘', 60, sysdate, to_date('2022-08-03','YYYY-MM-DD'), 200000);
SELECT * FROM SCHEDULE;
/*
일정 생성
INSERT INTO SCHEDULE values(seq_sno.nextval, #{pno}, #{sname}, #{progress}, 
							to_date(#{startDate_s}, 'YYYY-MM-DD'), to_date(#{endDate_s}, 'YYYY-MM-DD'));
*/
SELECT * FROM SCHEDULE;
SELECT *
FROM SCHEDULE
WHERE PNO = 2
ORDER BY SNO;
SELECT AVG(progress)
FROM SCHEDULE
WHERE pno = 2;

SELECT p.TITLE, p.DEPT, p.PMNO, s.* 
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO
AND p.PMNO = 'E10000004';

SELECT p.DEPT, count(*) 
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO
AND p.PMNO = 'E10000004'
GROUP BY p.DEPT;

SELECT p.TITLE, p.DEPT, s.*
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO;

SELECT SNO, SNAME, 
	TO_NUMBER(TO_CHAR(STARTDATE, 'YYYY')) SY, TO_NUMBER(TO_CHAR(STARTDATE, 'MM')) SM, TO_NUMBER(TO_CHAR(STARTDATE, 'DD')) SD,
	TO_NUMBER(TO_CHAR(ENDDATE, 'YYYY')) EY, TO_NUMBER(TO_CHAR(ENDDATE, 'MM')) EM, TO_NUMBER(TO_CHAR(ENDDATE, 'DD')) ED,
	PROGRESS
FROM SCHEDULE
WHERE PNO = 2;

SELECT SNO, SNAME, STARTDATE, ENDDATE, PROGRESS
FROM SCHEDULE
WHERE PNO = 2;

UPDATE SCHEDULE
	SET STARTDATE = TO_DATE('2022-07-10', 'YYYY-MM-DD'),
		ENDDATE = SYSDATE 
WHERE SNO = 3;
/*
프로젝트 별 일정 리스트 
SELECT *
FROM SCHEDULE
WHERE pno = #{pno}

관리하는 모든 일정리스트(pm)
SELECT p.TITLE, p.DEPT, p.PMNO, s.* 
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO
AND p.PMNO = #{pmno}

모든 일정 보기
SELECT p.TITLE, p.DEPT, s.*
FROM PROJECT p, SCHEDULE s
WHERE p.PNO = s.PNO

간트차트용 일정 데이터
SELECT SNO, SNAME, 
	TO_NUMBER(TO_CHAR(STARTDATE, 'YYYY')) SY, TO_NUMBER(TO_CHAR(STARTDATE, 'MM')) SM, TO_NUMBER(TO_CHAR(STARTDATE, 'DD')) SD,
	TO_NUMBER(TO_CHAR(ENDDATE, 'YYYY')) EY, TO_NUMBER(TO_CHAR(ENDDATE, 'MM')) EM, TO_NUMBER(TO_CHAR(ENDDATE, 'DD')) ED,
	PROGRESS
FROM SCHEDULE
WHERE PNO = #{pno}

SELECT SNO, SNAME, TO_DATE(STARTDATE), TO_DATE(ENDDATE), PROGRESS
FROM SCHEDULE
WHERE PNO = #{pno}
*/




/*
 * 프로젝트 참가자
 */
CREATE TABLE PRJPARTICIPANT (
	userno varchar2(9) NOT NULL,
	pno NUMBER NOT NULL
);
INSERT INTO PRJPARTICIPANT values('E10000020', 2);
INSERT INTO PRJPARTICIPANT values('E10000004', 21);

DELETE FROM PRJPARTICIPANT 
WHERE PNO = #{PNO} AND USERNO = #{USERNO}

SELECT * FROM PRJPARTICIPANT
WHERE pno = 2;

SELECT DISTINCT
	  pj.*
FROM PROJECT pj, PRJPARTICIPANT p, SCHEDULE s 
WHERE pj.PNO = p.PNO AND s.PNO  = p.PNO
AND p.USERNO = 'E10000020';

SELECT p.*
FROM PROJECT p, PRJPARTICIPANT pp
WHERE p.PNO = pp.PNO
AND pp.USERNO = 'E10000004';

SELECT * FROM PRJPARTICIPANT;
/*
프로젝트 참가자 추가
INSERT INTO PRJPARTICIPANT values(#{userno}, #{pno})

내 프로젝트 보기
SELECT p.*, AVG(progress) 
FROM PROJECT p, PRJPARTICIPANT pp, SCHEDULE s
WHERE p.PNO = pp.PNO AND p.PNO = s.PNO(+)
AND pp.USERNO = #{userno}
GROUP BY p.PNO, p.TITLE, p.DEPT, p.PMNO

프로젝트 참가자 목록
SELECT a.*
FROM ACCOUNT a, PRJPARTICIPANT p 
WHERE a.USERNO = p.USERNO
AND p.PNO = #{pno}

프로젝트 참가자 삭제
DELETE FROM PRJPARTICIPANT 
WHERE PNO = #{PNO} AND USERNO = #{USERNO}
 */


SELECT PNO, AVG(PROGRESS) 
FROM SCHEDULE
GROUP BY pno;

SELECT a.*
FROM ACCOUNT a, PRJPARTICIPANT p 
WHERE a.USERNO = p.USERNO
AND p.PNO = 2;

/*
 * 일정 참가자
 */
CREATE TABLE SCHPARTICIPANT (
	userno varchar2(9) NOT NULL,
	sno NUMBER NOT NULL,
	pno NUMBER NOT NULL
);
INSERT INTO SCHPARTICIPANT values('E10000004', 21, 21);
INSERT INTO SCHPARTICIPANT values('E10000020', 3, 2);
/*
일정 참가자 추가
INSERT INTO SCHPARTICIPANT values(#{userno}, #{sno}, #{pno})

일정 참가자 목록
SELECT s.SNO, a.USERNO, a.NAME, a.POSITION, a.DEPT
FROM SCHPARTICIPANT s, ACCOUNT a
WHERE s.USERNO = a.USERNO 
AND sno = #{sno}

일정 참가자 삭제
DELETE FROM SCHPARTICIPANT
WHERE sno = #{sno} AND USERNO = #{userno}

일정 참가자 삭제(프로젝트용)
DELETE FROM SCHPARTICIPANT
WHERE pno = #{pno} AND USERNO = #{userno}
*/
SELECT * FROM SCHPARTICIPANT
ORDER BY USERNO, pno;

DELETE FROM SCHPARTICIPANT
WHERE sno = 164 AND USERNO = ;

SELECT s.PNO, s.SNO, a.USERNO, a.NAME, a.POSITION, a.DEPT
FROM SCHPARTICIPANT s, ACCOUNT a
WHERE s.USERNO = a.USERNO 
AND sno = 2;

SELECT p.USERNO, pj.TITLE, pj.DEPT, s.*
FROM SCHEDULE s, PROJECT pj, SCHPARTICIPANT p
WHERE pj.PNO = s.PNO AND pj.PNO = p.PNO AND s.SNO = p.SNO
AND p.USERNO = 'E10000020';


SELECT pno, AVG(progress)
FROM SCHEDULE
GROUP BY PNO;
/*
내 업무 보기
SELECT p.USERNO, pj.TITLE, pj.DEPT, s.*
FROM SCHEDULE s, PROJECT pj, SCHPARTICIPANT p
WHERE pj.PNO = s.PNO AND pj.PNO = p.PNO AND s.SNO = p.SNO
AND p.USERNO = #{userno}
*/